name: Build and Static Code Analysis On Pull Request
on:
  pull_request:
    branches: [ "develop" ]
jobs:
  Build_and_analyse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Setup JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'

    - name: Test with Maven
      run: mvn test

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: Java        

    - name: Build with Maven
      run: mvn clean install

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2